---
title: "World Propulation Gapminder Clean & tidy"
author: "Alex"
date: "6 April 2016"
output: html_document
---

```{r}
setwd('/home/rstudio/worldpopulation/')
Sys.setlocale("LC_TIME", "en_US.UTF-8")
library(tidyr)
```

```{r}
df <- read.csv('World_population.csv', 
               sep = ";",check.names=FALSE, 
               stringsAsFactors=FALSE,  
               na.strings=c("","NA"))
id <- read.csv('idCountry_2.csv', 
               sep = ";",check.names=FALSE, 
               stringsAsFactors=FALSE,  
               na.strings=c("","NA"),
               colClasses=c("ISO3166-N"="character"))
```

```{r}
tdf <- gather(df, "Year", "Population", -1, na.rm = TRUE)
```

```{r}
tdf$Population <- sapply(tdf$Population, function(pop) as.numeric(gsub(",", "", pop)))
```

```{r}
tdf <- tdf[with(tdf, order(Country, Year)), ]
```

```{r}
tdf <- inner_join(tdf, id, by= c("Country" = "Name"))
```

```{r}
tdf <- tdf[c("Country", "Continent", "Year", "Population", "ISO3166-2", "ISO3166-3", "ISO3166-N", "ContinentCode")]
```


```{r}
write.table(tdf, file = "World_population.tsv", sep = "\t", row.names = F)
```

